### ISSUE TITLE
Attempting to re-register an account that has already been registered causes an error.

### ISSUE THREAD

**Issue by johnnymatthews** [entropyxyz/cli#193]
This is fairly obvious, but if you attempt to register an account that has previously been registered, you get an error, and are kicked out of the CLI:

```shell
2024-07-18 14:46:21        REGISTRY: Unknown signed extensions ValidateConfirmRegistered found, treating them as no-effect
2024-07-18 14:46:21        API/INIT: RPC methods not decorated: chainSpec_v1_chainName, chainSpec_v1_genesisHash, chainSpec_v1_properties
Attempting to register the address: 5DSUAf2DwxW2ebZq15Pm6Z3SJ69Ur8fGd8ytWvgxvNjYtr7c
undefined:1


SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at get (file:///home/io/.local/share/pnpm/global/5/.pnpm/@entropyxyz+cli@0.0.3/node_modules/@entropyxyz/cli/dist/cli.js:176:15)
    at async EventEmitter.<anonymous> (file:///home/io/.local/share/pnpm/global/5/.pnpm/@entropyxyz+cli@0.0.3/node_modules/@entropyxyz/cli/dist/cli.js:401:23)

Node.js v22.3.0
```

## Tasks

- [ ] Catch the error before the user is thrown out of the CLI.
- [ ] Tell the user that you can't register an account more than once.

**Comment by rh0delta** [comment]
Register errors are being captured and handled appropriately without kicking the user out of the CLI, as of v0.1.0. As well, users are able to register multiple times on the same account, closing this issue for now.
cc: @johnnymatthews
