### ISSUE TITLE
`entropy balance <address>` should take any address

### ISSUE THREAD

**Issue by frankiebee** [entropyxyz/cli#237]
right now you have to have the address in your config but that command should take any address.

**Comment by rh0delta** [comment]
@frankiebee should we discuss exposing substrate as part of the Entropy class rather than the instance? or were you thinking of another workaround for this?

**Comment by rh0delta** [comment]
duplicates #115

**Comment by mixmix** [comment]
Example:

```
➜  sdk git:(main) entropy balance 5GpDAn3x37k8Krd9wfsW8Tf6DxWgPJg5e8hXB3dj3ZGtod6h
18,748,620,727 BITS%                                                                                                                                                                                                                                           ➜  sdk git:(main) 
➜  sdk git:(main) rm -rf ~/.config/entropy-cryptography 
➜  sdk git:(main) entropy balance 5GpDAn3x37k8Krd9wfsW8Tf6DxWgPJg5e8hXB3dj3ZGtod6h
file:///home/ENTROPY/cli/dist/cli.js:3736
    throw new Error(`No account with name or address: "${addressOrName}"`);
          ^

Error: No account with name or address: "5GpDAn3x37k8Krd9wfsW8Tf6DxWgPJg5e8hXB3dj3ZGtod6h"
    at loadEntropy (file:///home/ENTROPY/cli/dist/cli.js:3736:11)
    at Command.<anonymous> (file:///home/ENTROPY/cli/dist/cli.js:12091:27)
    at Command.listener [as _actionHandler] (/home/ENTROPY/cli/node_modules/commander/lib/command.js:542:17)
    at /home/ENTROPY/cli/node_modules/commander/lib/command.js:1502:14
    at /home/ENTROPY/cli/node_modules/commander/lib/command.js:1383:33
    at async Command.parseAsync (/home/ENTROPY/cli/node_modules/commander/lib/command.js:1092:5)

Node.js v20.10.0

```

**Comment by mixmix** [comment]
I think this is something we will not support in TUI

**Comment by mixmix** [comment]
Feature merged into `dev`, about to be released. Closing this now
