### ISSUE TITLE
Allow users to not add schema files.

### ISSUE THREAD

**Issue by johnnymatthews** [entropyxyz/cli#312]
Currently the CLI requires that users add the path to their auxilary and config schemas. This isn't strictly necessary, as programs can be deployed without them. There's a [similar issue over in the the Entropy Core repo](https://github.com/entropyxyz/entropy-core/issues/1085) to remove the need for these files.

**Comment by johnnymatthews** [comment]
Gotcha.

I tried supplying the CLI with a couple of empty `.json` files, but it didn't like that:

```
Deployment failed: SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at file:///home/johnny/Code/entropy/cli/dist/cli.js:11428:71
    at async EntropyProgram.deploy (file:///home/johnny/Code/entropy/cli/dist/cli.js:11535:33)
    at async deployProgramTUI (file:///home/johnny/Code/entropy/cli/dist/cli.js:11862:21)
    at async entropyProgramDev (file:///home/johnny/Code/entropy/cli/dist/cli.js:11831:3)
    at async main (file:///home/johnny/Code/entropy/cli/dist/cli.js:12001:9)
```

Understandable since I think the CLI uses those files to display info back to the user.

**Comment by johnnymatthews** [comment]
Turns out you can use a couple of empty json blocks:

```shell
echo "{}" > auxiliary_data.json && echo "{}" > configuration.json
```

You can then use these in the CLI to deploy a program.
