### ISSUE TITLE
Non persistance of new accounts

### ISSUE THREAD

**Issue by JesseAbram** [entropyxyz/cli#326]
I create a new key on the current testnet (register), go to sign and it works, while it is in the same process. But when I exit the process and come back I get a not registered error. 

I can start the registration again and it works, now my config has been consistent through a few versions, and I have tried switching which account is selected but no joy as of yet

**Comment by rh0delta** [comment]
`file:///Users/nayyirjutha/Development/Entropy/cli/node_modules/@entropyxyz/sdk/dist/index.js:440
    const [sig, proof] = sigsAndProofs[Math.floor(Math.random() * sigsAndProofs.length)];
                         ^

TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at #verifyAndPick (file:///Users/nayyirjutha/Development/Entropy/cli/node_modules/@entropyxyz/sdk/dist/index.js:440:26)
    at SignatureRequestManager.sign (file:///Users/nayyirjutha/Development/Entropy/cli/node_modules/@entropyxyz/sdk/dist/index.js:330:48)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SignatureRequestManager.signWithAdaptersInOrder (file:///Users/nayyirjutha/Development/Entropy/cli/node_modules/@entropyxyz/sdk/dist/index.js:292:23)
    at async Entropy.signWithAdaptersInOrder (file:///Users/nayyirjutha/Development/Entropy/cli/node_modules/@entropyxyz/sdk/dist/index.js:844:12)
    at async EntropySign.signMessageWithAdapters (file:///Users/nayyirjutha/Development/Entropy/cli/dist/cli.js:11370:29)
    at async Command.<anonymous> (file:///Users/nayyirjutha/Development/Entropy/cli/dist/cli.js:12292:27)
    at async Command.parseAsync (/Users/nayyirjutha/Development/Entropy/cli/node_modules/commander/lib/command.js:1092:5)`

**Comment by rh0delta** [comment]
> ```file:///Users/nayyirjutha/Development/Entropy/cli/node_modules/@entropyxyz/sdk/dist/index.js:440
> 
>     const [sig, proof] = sigsAndProofs[Math.floor(Math.random() * sigsAndProofs.length)];
> 
>                          ^
> 
> 
> 
> TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
> 
>     at #verifyAndPick (file:///Users/nayyirjutha/Development/Entropy/cli/node_modules/@entropyxyz/sdk/dist/index.js:440:26)
> 
>     at SignatureRequestManager.sign (file:///Users/nayyirjutha/Development/Entropy/cli/node_modules/@entropyxyz/sdk/dist/index.js:330:48)
> 
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
> 
>     at async SignatureRequestManager.signWithAdaptersInOrder (file:///Users/nayyirjutha/Development/Entropy/cli/node_modules/@entropyxyz/sdk/dist/index.js:292:23)
> 
>     at async Entropy.signWithAdaptersInOrder (file:///Users/nayyirjutha/Development/Entropy/cli/node_modules/@entropyxyz/sdk/dist/index.js:844:12)
> 
>     at async EntropySign.signMessageWithAdapters (file:///Users/nayyirjutha/Development/Entropy/cli/dist/cli.js:11370:29)
> 
>     at async Command.<anonymous> (file:///Users/nayyirjutha/Development/Entropy/cli/dist/cli.js:12292:27)
> 
>     at async Command.parseAsync (/Users/nayyirjutha/Development/Entropy/cli/node_modules/commander/lib/command.js:1092:5)```

Issue with reshare flow on core, fix will be in next release

**Comment by mixmix** [comment]
@JesseAbram to be able to debug this we need to know
1. what version of the cli are you using  `entropy -v`
2. how did you install it?
    - A) `npm install -g @entropyxyz/cli` ?
    - B) `git clone` + `yarn && yarn build` + ...

**Comment by mixmix** [comment]
> ```
> at sendHttpPost (file:///Users/jesse/Desktop/entropy/cli/node_modules/@entropyxyz/sdk/dist/chunk-A3UVA2EN.js:42:11)
> ```

If your stacktrace has not been edited, it looks like B - a manual/ dev install.
Ideally you are not testing that, and test the global install that we are releasing as "ready" (A). If you do want to give feedback we need to know the commit / tag you're sitting on

**Comment by mixmix** [comment]
I just reproduced this with `entropy sign "some string"`
