### ISSUE TITLE
Add more graceful error handling for common pathways

### ISSUE THREAD

**Issue by tuxxy** [entropyxyz/cli#81]
For example, when trying to sign without registering, you get a big blob:
```
/Users/tux/code/cli/node_modules/@entropyxyz/sdk/dist/index.cjs:12218
    throw new Error(
          ^
Error: request failed 500, Internal Server Error fetch: http://3.84.209.123:3001/user/sign_tx FULLRESPONSE: Chain Fetch: Not Registering error: Register Onchain first
    at sendHttpPost (/Users/tux/code/cli/node_modules/@entropyxyz/sdk/dist/index.cjs:12218:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/tux/code/cli/node_modules/@entropyxyz/sdk/dist/index.cjs:12769:26
    at async Promise.all (index 1)
    at async SignatureRequestManager.sign (/Users/tux/code/cli/node_modules/@entropyxyz/sdk/dist/index.cjs:12670:18)
    at async SignatureRequestManager.signWithAdaptersInOrder (/Users/tux/code/cli/node_modules/@entropyxyz/sdk/dist/index.cjs:12636:23)
    at async Entropy.signWithAdaptersInOrder (/Users/tux/code/cli/node_modules/@entropyxyz/sdk/dist/index.cjs:13186:12)
    at async Object.sign (/Users/tux/code/cli/src/flows/sign/index.ts:91:24)
    at async main (/Users/tux/code/cli/src/index.ts:89:30)
error Command failed with exit code 1.
```

We should identify these common UX errors and give more graceful error messages for them rather than erroring all ugly.

**Comment by mixmix** [comment]
Here's a map of the ones I've found / we need to test:
- https://github.com/entropyxyz/cli/issues/295
- https://github.com/entropyxyz/cli/issues/296
- https://github.com/entropyxyz/cli/issues/297
- https://github.com/entropyxyz/cli/issues/300
- https://github.com/entropyxyz/cli/issues/299

Ones that look fine to me
- `entropy account create`
- `entropy account import`
- `entropy account register`
- `entropy balance`

---

closing this issue as we have spawned child issues tracking work needed
